---
- name: Download OneAgent installer in specific version to a custom
    directory with additional OneAgent install parameters. Both linux_other
    and linux_arm have different user specified by platform args parameter.
  vars_files:
    - "/etc/ansible/vault_credentials"
  hosts: AWS
  become: true
  no_log: false
  collections:
    - dynatrace.oneagent
  vars:
    oneagent_version: latest
    oneagent_install_args:
      - INSTALL_PATH=/opt/example
      - --set-host-group=dynatrace-web-dev
      - --set-network-zone=aws.us-east-1.dynatrace
  tasks:
    - import_role:
        name: oneagent
